version: "3.7"

services:
  bdd:
    # build:
      #ontext: .
      #dockerfile: Dockerfile
    image: melvin77290/postgresql-image
    command: ["su", "postgres", "-c", "postgres -D /var/lib/postgresql/data"]
    ports:
      - "5432:5432"
    networks:
      - dockerProject
      - default

  addminer:
    image: juleslance/adminer-alpine
    ports:
      - "8080:80"

networks:
  dockerProject:
    external: true