version: "3.7"

services:
  composer:
    image: juleslance/composer-alpine
    volumes:
      - ../../.:/srv
    working_dir: /srv
    command: composer install
  symfony:
    image: naegato/symfony-docker:latest
    depends_on:
      composer:
        condition: service_completed_successfully
    working_dir: /srv
    ports:
      - "8000:80"
    volumes:
      - ../../.:/srv
    command: "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    networks:
      - dockerProject
      - default

networks:
  dockerProject:
    external: true